### ISSUE TITLE
Update requirements.txt / build instructions

### ISSUE THREAD

**Issue by Yolandeezy** [SkyTruth/pybossa_tools#17]
The `requirements.txt` file is not pip installable. In order to get it to work, I had to comment out the following lines: 

```
distribute==0.6.34
swissarmykitchensink
```

**Comment by redhog** [comment]
swissarmykitchensink=>0.0.3

should work... otherwize please tell me how it breaks / the error message

**Comment by redhog** [comment]
The solution is to run

pip install --allow-external jsonpath --allow-unverified jsonpath -r requirements.txt 

This is due to changes in pip, and that the jsonpath package hasn't been updated to reflect this.
