### ISSUE TITLE
Verify that output from pad delineator is valid and as expected

### ISSUE THREAD

**Issue by geowurster** [SkyTruth/pybossa_tools#4]

**Comment by geowurster** [comment]
@ezys @redhog has anyone a couple dozen tasks in any application?  I need test data to close this one out.

**Comment by ezys** [comment]
@geowurster Can you clarify your last comment? I thought I had done a bunch in http://crowd.dev.skytruth.org/app/testegil/ but I only see 7 done. Or do you need me to get a bunch of different users to test it?

**Comment by geowurster** [comment]
One user is fine.  I just need some output to verify that the tasks are generating a usable output.  I’m mostly want to be sure that the geometry is being properly recorded.  Could you do some in this test app?

http://crowd.dev.skytruth.org/app/k-test4/settings


Kevin Wurster Geospatial Systems Engineer www.skytruth.org    
Office: +1 304 885 4581 | Skype: kwurst01 | kevin@skytruth.org

**Comment by ezys** [comment]
That's weird. Now it shows I've done 130 in that app, which sounds about right. That should be more than enough for you.
